#pragma checksum "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\_ViewStart.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7E37180E0F5CF7BF65B5FCCDBF305E88B647A79EBBA7B0A43B2826A818FFEC4C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using BooksAPI;
    
    
    public class _Page_Views__ViewStart_cshtml : System.Web.Mvc.ViewStartPage {
        
#line hidden
        
        public _Page_Views__ViewStart_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\_ViewStart.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
BeginContext("~/Views/_ViewStart.cshtml", 52, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/_ViewStart.cshtml", 52, 2, true);

        }
    }
}
