#pragma checksum "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "55B73B0A827118BA7073125438D03BE79804D88769C09041E605AFF6144D3FAE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using BooksAPI;
    
    
    public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__Layout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_Layout.cshtml", 0, 42, true);

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 0, 42, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 42, 16, true);

WriteLiteral(" charset=\"utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 42, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 58, 14, true);

WriteLiteral(" />\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 58, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 72, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/_Layout.cshtml", 72, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 88, 29, true);

WriteLiteral(" content=\"width=device-width\"");

EndContext("~/Views/Shared/_Layout.cshtml", 88, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 117, 16, true);

WriteLiteral(" />\r\n    <title>");

EndContext("~/Views/Shared/_Layout.cshtml", 117, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 134, 13, false);

            
            #line 6 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 134, 13, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 147, 35, true);

WriteLiteral(" - My ASP.NET Application</title>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 147, 35, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 182, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 182, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 187, 30, false);

            
            #line 7 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 187, 30, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 217, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 217, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 219, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 219, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 224, 37, false);

            
            #line 8 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 224, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 261, 29, true);

WriteLiteral("\r\n</head>\r\n<body>\r\n\r\n    <nav");

EndContext("~/Views/Shared/_Layout.cshtml", 261, 29, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 290, 73, true);

WriteLiteral(" class=\"navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark\"");

EndContext("~/Views/Shared/_Layout.cshtml", 290, 73, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 363, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Shared/_Layout.cshtml", 363, 15, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 378, 18, true);

WriteLiteral(" class=\"container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 378, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 396, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 396, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 399, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Shared/_Layout.cshtml", 399, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 412, 104, false);

            
            #line 14 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
       Write(Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 412, 104, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 516, 21, true);

WriteLiteral("\r\n            <button");

EndContext("~/Views/Shared/_Layout.cshtml", 516, 21, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 537, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Shared/_Layout.cshtml", 537, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 551, 23, true);

WriteLiteral(" class=\"navbar-toggler\"");

EndContext("~/Views/Shared/_Layout.cshtml", 551, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 574, 26, true);

WriteLiteral(" data-bs-toggle=\"collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 574, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 600, 34, true);

WriteLiteral(" data-bs-target=\".navbar-collapse\"");

EndContext("~/Views/Shared/_Layout.cshtml", 600, 34, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 634, 26, true);

WriteLiteral(" title=\"Toggle navigation\"");

EndContext("~/Views/Shared/_Layout.cshtml", 634, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 660, 39, true);

WriteLiteral(" aria-controls=\"navbarSupportedContent\"");

EndContext("~/Views/Shared/_Layout.cshtml", 660, 39, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 699, 43, true);

WriteLiteral("\r\n                    aria-expanded=\"false\"");

EndContext("~/Views/Shared/_Layout.cshtml", 699, 43, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 742, 31, true);

WriteLiteral(" aria-label=\"Toggle navigation\"");

EndContext("~/Views/Shared/_Layout.cshtml", 742, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 773, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Shared/_Layout.cshtml", 773, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 797, 28, true);

WriteLiteral(" class=\"navbar-toggler-icon\"");

EndContext("~/Views/Shared/_Layout.cshtml", 797, 28, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 825, 49, true);

WriteLiteral("></span>\r\n            </button>\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 825, 49, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 874, 74, true);

WriteLiteral(" class=\"collapse navbar-collapse d-sm-inline-flex justify-content-between\"");

EndContext("~/Views/Shared/_Layout.cshtml", 874, 74, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 948, 22, true);

WriteLiteral(">\r\n                <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 948, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 970, 31, true);

WriteLiteral(" class=\"navbar-nav flex-grow-1\"");

EndContext("~/Views/Shared/_Layout.cshtml", 970, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1001, 27, true);

WriteLiteral(">\r\n                    <li>");

EndContext("~/Views/Shared/_Layout.cshtml", 1001, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1029, 88, false);

            
            #line 21 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1029, 88, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1117, 31, true);

WriteLiteral("</li>\r\n                    <li>");

EndContext("~/Views/Shared/_Layout.cshtml", 1117, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1149, 87, false);

            
            #line 22 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("API", "Index", "Help", new { area = "" }, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1149, 87, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1236, 86, true);

WriteLiteral("</li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n    </nav>\r\n   " +
" <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1236, 86, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1322, 31, true);

WriteLiteral(" class=\"container body-content\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1322, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1353, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1353, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1356, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Shared/_Layout.cshtml", 1356, 8, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1365, 12, false);

            
            #line 28 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1365, 12, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1377, 58, true);

WriteLiteral("\r\n        <hr />\r\n        <footer>\r\n            <p>&copy; ");

EndContext("~/Views/Shared/_Layout.cshtml", 1377, 58, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1436, 17, false);

            
            #line 31 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1436, 17, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1453, 64, true);

WriteLiteral(" - My ASP.NET Application</p>\r\n        </footer>\r\n    </div>\r\n\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1453, 64, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1517, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1517, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1522, 34, false);

            
            #line 35 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1522, 34, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1556, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1556, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1558, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1558, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1563, 37, false);

            
            #line 36 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1563, 37, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1600, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1600, 2, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1602, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1602, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1607, 41, false);

            
            #line 37 "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1607, 41, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1648, 20, true);

WriteLiteral("\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1648, 20, true);

        }
    }
}
