#pragma checksum "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Shared\Error.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "ECFBBAB01561A320C9DF392CB935E382DFA6E16D3C2EB3F23823F228A10ABB22"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using BooksAPI;
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/Error.cshtml", 0, 42, true);

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

EndContext("~/Views/Shared/Error.cshtml", 0, 42, true);

BeginContext("~/Views/Shared/Error.cshtml", 42, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/Error.cshtml", 42, 16, true);

BeginContext("~/Views/Shared/Error.cshtml", 58, 29, true);

WriteLiteral(" content=\"width=device-width\"");

EndContext("~/Views/Shared/Error.cshtml", 58, 29, true);

BeginContext("~/Views/Shared/Error.cshtml", 87, 187, true);

WriteLiteral(" />\r\n    <title>Error</title>\r\n</head>\r\n<body>\r\n    <hgroup>\r\n        <h1>Error.<" +
"/h1>\r\n        <h2>An error occurred while processing your request.</h2>\r\n    </h" +
"group>\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Shared/Error.cshtml", 87, 187, true);

        }
    }
}
