#pragma checksum "C:\Users\linhh\source\repos\BooksAPI\BooksAPI\Views\Home\Index.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4ECC276EC0F5B6E6DF7B692DFC13698AC5CB145083E4C57DC630E9153B6B304E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using BooksAPI;
    
    
    public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/Index.cshtml", 0, 20, true);

WriteLiteral("<main>\r\n    <section");

EndContext("~/Views/Home/Index.cshtml", 0, 20, true);

BeginContext("~/Views/Home/Index.cshtml", 20, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Home/Index.cshtml", 20, 12, true);

BeginContext("~/Views/Home/Index.cshtml", 32, 30, true);

WriteLiteral(" aria-labelledby=\"aspnetTitle\"");

EndContext("~/Views/Home/Index.cshtml", 32, 30, true);

BeginContext("~/Views/Home/Index.cshtml", 62, 14, true);

WriteLiteral(">\r\n        <h1");

EndContext("~/Views/Home/Index.cshtml", 62, 14, true);

BeginContext("~/Views/Home/Index.cshtml", 76, 17, true);

WriteLiteral(" id=\"aspnetTitle\"");

EndContext("~/Views/Home/Index.cshtml", 76, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 93, 25, true);

WriteLiteral(">ASP.NET</h1>\r\n        <p");

EndContext("~/Views/Home/Index.cshtml", 93, 25, true);

BeginContext("~/Views/Home/Index.cshtml", 118, 13, true);

WriteLiteral(" class=\"lead\"");

EndContext("~/Views/Home/Index.cshtml", 118, 13, true);

BeginContext("~/Views/Home/Index.cshtml", 131, 134, true);

WriteLiteral(">ASP.NET is a free web framework for building great Web sites and Web application" +
"s using HTML, CSS, and JavaScript.</p>\r\n        <p><a");

EndContext("~/Views/Home/Index.cshtml", 131, 134, true);

BeginContext("~/Views/Home/Index.cshtml", 265, 23, true);

WriteLiteral(" href=\"https://asp.net\"");

EndContext("~/Views/Home/Index.cshtml", 265, 23, true);

BeginContext("~/Views/Home/Index.cshtml", 288, 31, true);

WriteLiteral(" class=\"btn btn-primary btn-md\"");

EndContext("~/Views/Home/Index.cshtml", 288, 31, true);

BeginContext("~/Views/Home/Index.cshtml", 319, 53, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </section>\r\n    <div");

EndContext("~/Views/Home/Index.cshtml", 319, 53, true);

BeginContext("~/Views/Home/Index.cshtml", 372, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Home/Index.cshtml", 372, 12, true);

BeginContext("~/Views/Home/Index.cshtml", 384, 19, true);

WriteLiteral(">\r\n        <section");

EndContext("~/Views/Home/Index.cshtml", 384, 19, true);

BeginContext("~/Views/Home/Index.cshtml", 403, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/Index.cshtml", 403, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 420, 38, true);

WriteLiteral(" aria-labelledby=\"gettingStartedTitle\"");

EndContext("~/Views/Home/Index.cshtml", 420, 38, true);

BeginContext("~/Views/Home/Index.cshtml", 458, 18, true);

WriteLiteral(">\r\n            <h2");

EndContext("~/Views/Home/Index.cshtml", 458, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 476, 25, true);

WriteLiteral(" id=\"gettingStartedTitle\"");

EndContext("~/Views/Home/Index.cshtml", 476, 25, true);

BeginContext("~/Views/Home/Index.cshtml", 501, 329, true);

WriteLiteral(@">Getting started</h2>
            <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
            a broad range of clients, including browsers and mobile devices. ASP.NET Web API
            is an ideal platform for building RESTful applications on the .NET Framework.</p>
            <p><a");

EndContext("~/Views/Home/Index.cshtml", 501, 329, true);

BeginContext("~/Views/Home/Index.cshtml", 830, 29, true);

WriteLiteral(" class=\"btn btn-outline-dark\"");

EndContext("~/Views/Home/Index.cshtml", 830, 29, true);

BeginContext("~/Views/Home/Index.cshtml", 859, 54, true);

WriteLiteral(" href=\"https://go.microsoft.com/fwlink/?LinkId=301870\"");

EndContext("~/Views/Home/Index.cshtml", 859, 54, true);

BeginContext("~/Views/Home/Index.cshtml", 913, 65, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n        </section>\r\n        <section");

EndContext("~/Views/Home/Index.cshtml", 913, 65, true);

BeginContext("~/Views/Home/Index.cshtml", 978, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/Index.cshtml", 978, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 995, 33, true);

WriteLiteral(" aria-labelledby=\"librariesTitle\"");

EndContext("~/Views/Home/Index.cshtml", 995, 33, true);

BeginContext("~/Views/Home/Index.cshtml", 1028, 18, true);

WriteLiteral(">\r\n            <h2");

EndContext("~/Views/Home/Index.cshtml", 1028, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 1046, 20, true);

WriteLiteral(" id=\"librariesTitle\"");

EndContext("~/Views/Home/Index.cshtml", 1046, 20, true);

BeginContext("~/Views/Home/Index.cshtml", 1066, 196, true);

WriteLiteral(">Get more libraries</h2>\r\n            <p>NuGet is a free Visual Studio extension " +
"that makes it easy to add, remove, and update libraries and tools in Visual Stud" +
"io projects.</p>\r\n            <p><a");

EndContext("~/Views/Home/Index.cshtml", 1066, 196, true);

BeginContext("~/Views/Home/Index.cshtml", 1262, 29, true);

WriteLiteral(" class=\"btn btn-outline-dark\"");

EndContext("~/Views/Home/Index.cshtml", 1262, 29, true);

BeginContext("~/Views/Home/Index.cshtml", 1291, 54, true);

WriteLiteral(" href=\"https://go.microsoft.com/fwlink/?LinkId=301871\"");

EndContext("~/Views/Home/Index.cshtml", 1291, 54, true);

BeginContext("~/Views/Home/Index.cshtml", 1345, 65, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n        </section>\r\n        <section");

EndContext("~/Views/Home/Index.cshtml", 1345, 65, true);

BeginContext("~/Views/Home/Index.cshtml", 1410, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/Home/Index.cshtml", 1410, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 1427, 31, true);

WriteLiteral(" aria-labelledby=\"hostingTitle\"");

EndContext("~/Views/Home/Index.cshtml", 1427, 31, true);

BeginContext("~/Views/Home/Index.cshtml", 1458, 18, true);

WriteLiteral(">\r\n            <h2");

EndContext("~/Views/Home/Index.cshtml", 1458, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 1476, 18, true);

WriteLiteral(" id=\"hostingTitle\"");

EndContext("~/Views/Home/Index.cshtml", 1476, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 1494, 169, true);

WriteLiteral(">Web Hosting</h2>\r\n            <p>You can easily find a web hosting company that " +
"offers the right mix of features and price for your applications.</p>\r\n         " +
"   <p><a");

EndContext("~/Views/Home/Index.cshtml", 1494, 169, true);

BeginContext("~/Views/Home/Index.cshtml", 1663, 29, true);

WriteLiteral(" class=\"btn btn-outline-dark\"");

EndContext("~/Views/Home/Index.cshtml", 1663, 29, true);

BeginContext("~/Views/Home/Index.cshtml", 1692, 54, true);

WriteLiteral(" href=\"https://go.microsoft.com/fwlink/?LinkId=301872\"");

EndContext("~/Views/Home/Index.cshtml", 1692, 54, true);

BeginContext("~/Views/Home/Index.cshtml", 1746, 69, true);

WriteLiteral(">Learn more &raquo;</a></p>\r\n        </section>>\r\n    </div>\r\n</main>");

EndContext("~/Views/Home/Index.cshtml", 1746, 69, true);

        }
    }
}
